//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PsiSiDlg.rc
//
#define IDD_PAT_PMT                     101
#define IDD_AddDescriptor               102
#define IDD_ProgramPid                  103
#define IDD_Desc_data_broadcast_id_descriptor 104
#define IDD_NIT_SDT                     105
#define IDD_Service                     106
#define IDD_Desc_unsupported            111
#define IDD_EditValue                   112
#define IDD_Wizard                      113
#define IDD_ADDPRGWIZ_1                 114
#define IDD_ADDPRGWIZ_2                 115
#define IDD_ADDPRGWIZ_3                 116
#define IDD_NewNtwWiz_1                 118
#define IDD_NewNtwWiz_2                 119
#define IDD_NewNtwWiz_Sat               120
#define IDD_NewNtwWiz_Cable             121
#define IDD_NewNtwWiz_Ter               122
#define IDD_DeliveryEdit                123
#define IDD_LanguageDlg                 124
#define IDD_CountryAvail                125
#define IDD_MultiLingName               126
#define IDC_LST_Programs                1000
#define IDC_BTN_AddProgram              1001
#define IDC_BTN_DeleteProgram           1002
#define IDC_CHK_ProgramMapping          1004
#define IDC_EDT_PcrPid                  1005
#define IDC_EDT_ProgramNumber           1006
#define IDC_LST_Descriptors             1007
#define IDC_BTN_AddDesc                 1008
#define IDC_BTN_DelDesc                 1009
#define IDC_LST_Streams                 1010
#define IDC_LST_StreamDescr             1011
#define IDC_BTN_DelTSDesc               1011
#define IDC_BTN_AddStreamDesc           1012
#define IDC_BTN_AddTS                   1012
#define IDC_BTN_DelStreamDesc           1013
#define IDC_BTN_DelTS                   1013
#define IDC_BTN_AddStream               1014
#define IDC_BTN_AddServDesc             1014
#define IDC_BTN_DelStream               1015
#define IDC_BTN_DelServDesc             1015
#define IDC_BTN_AddService              1016
#define IDC_EDT_StreamPid               1017
#define IDC_BTN_DelService              1017
#define IDC_RDB_PcrPidHex               1018
#define IDC_RDB_PcrPidDec               1019
#define IDC_LST_DescrType               1020
#define IDC_RDB_ElemPidHex              1020
#define IDC_RDB_ElemPidDec              1021
#define IDC_EDT_ProgramPid              1022
#define IDC_RDB_PrgPidHex               1023
#define IDC_RDB_PrgPidDec               1024
#define IDC_LST_BroadcastID             1025
#define IDC_EDT_NetwrokID               1026
#define IDC_LST_TransportStreams        1027
#define IDC_LST_NetworkDesc             1028
#define IDC_LST_StreamDesc              1029
#define IDC_LST_Services                1032
#define IDC_LST_ServiceDesc             1034
#define IDC_CHK_FreeCAMode              1035
#define IDC_CB_RunningStatus            1036
#define IDC_CHK_EventSchedPresent       1037
#define IDC_CHK_EventFollowPresent      1038
#define IDC_EDT_ServiceId               1039
#define IDC_BTN_AddNtwDesc              1040
#define IDC_BTN_DelNtwDesc              1041
#define IDC_BTN_AddTSDesc               1042
#define IDC_EDT_TsID                    1043
#define IDC_EDT_TsOrigNetworkID         1044
#define IDC_CB_StreamType               1045
#define IDC_TsId                        1047
#define IDC_ItemName                    1049
#define IDC_edtValue                    1050
#define IDC_Description                 1051
#define IDC_cbValue                     1052
#define IDC_cbEditValue                 1053
#define IDC_PRGWIZ_PrgNum               1057
#define IDC_PRGWIZ_PmtPid               1058
#define IDC_PRGWIZ_PrgType              1060
#define IDC_PRGWIZ_ServName             1061
#define IDC_PRGWIZ_ServType             1062
#define IDC_PRGWIZ_ProvName             1063
#define IDC_PRGWIZ_ServId               1064
#define IDC_ADDPRGWIZ_StreamList        1065
#define IDC_ADDPRGWIZ_ElemPid           1068
#define IDC_ADDPRGWIZ_StreamType        1069
#define IDC_ADDPRGWIZ_DataBroadId       1070
#define IDC_ADDPRGWIZ_PcrPid            1071
#define IDC_ADDPRGWIZ_PcrPidEnabled     1072
#define IDC_NetworkName                 1073
#define IDC_cbNetworkId                 1074
#define IDC_NetwIdAsText                1076
#define IDC_cbOrigNetworkId             1078
#define IDC_OrigNetwIdAsText            1079
#define IDC_SatFreq                     1080
#define IDC_SatSymbRate                 1081
#define IDC_SatOrbitPos                 1082
#define IDC_cbSatPolar                  1083
#define IDC_SatWest                     1084
#define IDC_SatEast                     1085
#define IDC_cbFec                       1086
#define IDC_Cable                       1087
#define IDC_Satellite                   1088
#define IDC_Terrestrial                 1089
#define IDC_cbLanguage                  1090
#define IDC_cbAudioType                 1091
#define IDC_lstCountries                1091
#define IDC_lstAvailable                1092
#define IDC_lstNotAvailable             1093
#define IDC_AddAvail                    1094
#define IDC_RemoveAvail                 1095
#define IDC_lstLanguages                1095
#define IDC_AddNotAvail                 1096
#define IDC_edtName                     1096
#define IDC_RemoveNotAvail              1097
#define IDC_ProvLabel                   1097
#define IDC_edtProvider                 1098
#define IDC_btnAddLang                  1099
#define IDC_btnDelLang                  1100
#define ID_RefreshValueList             40000
#define ID_AddProgram                   40001
#define ID_AddProgramStream             40002
#define ID_RefreshTreeItem              40003
#define ID_NewNetwork                   40004
#define ID_CheckPidUnique               40005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
